### ISSUE TITLE
mybalance .auto spec bug

### ISSUE THREAD

**Issue by fb-rain** [dsverdlo/minqlx-plugins#2]
mybalance balance teams when count down 1.
After that,anyone joined the team will not be balanced.

**Comment by dsverdlo** [comment]
Hello fb-rain,

I moved the balancing to before a round, so that when teams were 4 vs 6, the players could be moved in time to still play the round 5 vs 5.

If someone joins after that, there is indeed no check... yet!
I'll add it later today and close the issue.

Thanks for reporting your thoughts on my plugin!
Have a good day
Iou

**Comment by dsverdlo** [comment]
Should be fixed with version 0.54.4

Now there will always be a check at the starting of a round too, in case someone joined at the last millisecond.

Cheers
Iou
